### ISSUE TITLE
Find the services and tables

### ISSUE THREAD

**Issue by abuccts** [abuccts/SDN-rootkit-detection#1]
@leahic questions can be asked at _opendaylight_ [form](https://ask.opendaylight.org/questions/) or use [IRC](https://wiki.opendaylight.org/view/IRC).

**Comment by leahic** [comment]
I asked a question in the "ask.opendaylight.org" . Maybe you can focus on it .
And i can't find your ask.

PS. what is the IRC ? It looks like a homework by Chinese students.

**Comment by abuccts** [comment]
@leahic  [IRC](https://en.wikipedia.org/wiki/Internet_Relay_Chat) is something like qq or wechat in China but much better and is widely used in open source community.
